Draft : Checkbox Control Function
Southeastern-Louisiana-University/docx-form pull request #18
Opened 2022-09-22 17:19 UTC by DannyBoy4u

2022-09-26 22:43 UTC, reecewbourgeois requested changes

2022-09-26 22:43 UTC, reecewbourgeois commented on docx_form/constants/__init__.py
> +from .constants import XML_CHECK
```suggestion
from .constants import XML_PREFIX, XML_CHECK
```

2022-09-26 22:43 UTC, reecewbourgeois commented on docx_form/content_controls/CheckBoxContentControl.py
> +    from constants import XML_CHECK
```suggestion
    from constants import XML_PREFIX, XML_CHECK
```

2022-09-26 22:43 UTC, reecewbourgeois commented on docx_form/content_controls/CheckBoxContentControl.py
> +        # Set values according to the boolean passed in
Please add documentation comments here. Use the others as an example so Sphinx can pick it up properly.

2022-09-26 23:43 UTC, reecewbourgeois approved these changes

2022-09-27 01:00 UTC, rmcclelen2 approved these changes

2022-09-27 16:14 UTC, rjherbert08 approved these changes

2022-09-27 16:16 UTC, merged