test: Added test for .save() method
Southeastern-Louisiana-University/docx-form pull request #46
Opened 2022-11-13 22:34 UTC by rmcclelen2

2022-11-13 23:08 UTC, DannyBoy4u reviewed
Beautiful

2022-11-13 23:08 UTC, DannyBoy4u approved these changes

2022-11-13 23:08 UTC, DannyBoy4u approved these changes

2022-11-13 23:11 UTC, reecewbourgeois commented on docx_form_tests/save_test.py
> +    test_changes = test.save("./docx_form_tests/test-m.docx")
```suggestion
    test.save("./docx_form_tests/test-m.docx")
```

2022-11-13 23:11 UTC, reecewbourgeois commented on docx_form_tests/save_test.py
> +    assert (new_contents != old_contents)
```suggestion
    assert (new_contents != old_contents)
    
    # Remove the test file created
    remove("./docx_form_tests/test-m.docx")
```

2022-11-13 23:12 UTC, reecewbourgeois commented on docx_form_tests/save_test.py
> +
```suggestion
from os import remove

```

2022-11-13 23:13 UTC, reecewbourgeois commented on docx_form_tests/save_test.py
> +    test_changes = test.save("./docx_form_tests/test-m.docx")
.save() doesn't have a return value, so this variable is not needed

2022-11-13 23:13 UTC, reecewbourgeois commented on docx_form_tests/save_test.py
> +    assert (new_contents != old_contents)
Just to clean up the file once the test is complete

2022-11-13 23:13 UTC, reecewbourgeois requested changes
test_changes is never used & .save doesn't have a return value

2022-11-13 23:18 UTC, reecewbourgeois approved these changes

2022-11-14 04:14 UTC, rjherbert08 approved these changes

2022-11-14 04:20 UTC, merged