test: Set option test
Southeastern-Louisiana-University/docx-form pull request #50
Opened 2022-11-15 01:32 UTC by rjherbert08

2022-11-15 01:35 UTC, rmcclelen2 approved these changes

2022-11-15 01:49 UTC, reecewbourgeois requested changes

2022-11-15 01:49 UTC, reecewbourgeois commented on docx_form_tests/set_options_test.py
> +    element.print_options()
not needed for a test

2022-11-15 17:46 UTC, reecewbourgeois approved these changes

2022-11-16 20:36 UTC, DannyBoy4u approved these changes

2022-11-16 20:56 UTC, merged